name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip folder
        run: git archive --prefix=${{ github.event.repository.name }}/ HEAD -o ${{ github.event.repository.name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}.zip